---
title: "Github Notebook"
output: html_document
editor_options: 
chunk_output_type: console
---

## Author:  Baxter Worthing
### Affiliation:  
### E-mail contact: 


### Start Date: 2020-01-13
### End Date: 2020-05-08
### Project Descriptions:   





# Table of Contents:  
  * [Entry 1: 2020-01-13, Monday](#id-section1)
      * [Entry 2: 2020-01-14, Tuesday](#id-section2)
    * [Entry 3: 2020-01-15, Wednesday](#id-section3)
     * [Entry 4: 2020-01-16, Thursday](#id-section4)
       * [Entry 5: 2020-01-17, Friday](#id-section5)
       * [Entry 6: 2020-01-20, Monday](#id-section6)
      * [Entry 7: 2020-01-21, Tuesday](#id-section7)
    * [Entry 8: 2020-01-22, Wednesday](#id-section8)
     * [Entry 9: 2020-01-23, Thursday](#id-section9)
    * [Entry 10: 2020-01-24, Friday](#id-section10)
    * [Entry 11: 2020-01-27, Monday](#id-section11)
     * [Entry 12: 2020-01-28, Tuesday](#id-section12)
     * [Entry 13: 2020-01-29, Wednesday](#id-section13)
     * [Entry 14: 2020-01-30, Thursday](#id-section14)
    * [Entry 15: 2020-01-31, Friday](#id-section15)
    * [Entry 16: 2020-02-03, Monday](#id-section16)
     * [Entry 17: 2020-02-04, Tuesday](#id-section17)
    * [Entry 18: 2020-02-05, Wednesday](#id-section18)
    * [Entry 19: 2020-02-06, Thursday](#id-section19)
    * [Entry 20: 2020-02-07, Friday](#id-section20)
    * [Entry 21: 2020-02-10, Monday](#id-section21)
    * [Entry 22: 2020-02-11, Tuesday](#id-section22)
     * [Entry 23: 2020-02-12, Wednesday](#id-section23)
    * [Entry 24: 2020-02-13, Thursday](#id-section24)
    * [Entry 25: 2020-02-14, Friday](#id-section25)
    * [Entry 26: 2020-02-17, Monday](#id-section26)
     * [Entry 27: 2020-02-18, Tuesday](#id-section27)
     * [Entry 28: 2020-02-19, Wednesday](#id-section28)
     * [Entry 29: 2020-02-20, Thursday](#id-section29)
    * [Entry 30: 2020-02-21, Friday](#id-section30)
    * [Entry 31: 2020-02-24, Monday](#id-section31)
    * [Entry 32: 2020-02-25, Tuesday](#id-section32)
     * [Entry 33: 2020-02-26, Wednesday](#id-section33)
    * [Entry 34: 2020-02-27, Thursday](#id-section34)
    * [Entry 35: 2020-02-28, Friday](#id-section35)
    * [Entry 36: 2020-03-02, Monday](#id-section36)
     * [Entry 37: 2020-03-03, Tuesday](#id-section37)
     * [Entry 38: 2020-03-04, Wednesday](#id-section38)
    * [Entry 39: 2020-03-05, Thursday](#id-section39)
    * [Entry 40: 2020-03-06, Friday](#id-section40)
    * [Entry 41: 2020-03-09, Monday](#id-section41)
    * [Entry 42: 2020-03-10, Tuesday](#id-section42)
     * [Entry 43: 2020-03-11, Wednesday](#id-section43)
    * [Entry 44: 2020-03-12, Thursday](#id-section44)
    * [Entry 45: 2020-03-13, Friday](#id-section45)
    * [Entry 46: 2020-03-16, Monday](#id-section46)
    * [Entry 47: 2020-03-17, Tuesday](#id-section47)
     * [Entry 48: 2020-03-18, Wednesday](#id-section48)
    * [Entry 49: 2020-03-19, Thursday](#id-section49)
    * [Entry 50: 2020-03-20, Friday](#id-section50)
    * [Entry 51: 2020-03-23, Monday](#id-section51)
     * [Entry 52: 2020-03-24, Tuesday](#id-section52)
     * [Entry 53: 2020-03-25, Wednesday](#id-section53)
     * [Entry 54: 2020-03-26, Thursday](#id-section54)
    * [Entry 55: 2020-03-27, Friday](#id-section55)
    * [Entry 56: 2020-03-30, Monday](#id-section56)
     * [Entry 57: 2020-03-31, Tuesday](#id-section57)
     * [Entry 58: 2020-04-01, Wednesday](#id-section58)
     * [Entry 59: 2020-04-02, Thursday](#id-section59)
    * [Entry 60: 2020-04-03, Friday](#id-section60)
    * [Entry 61: 2020-04-06, Monday](#id-section61)
     * [Entry 62: 2020-04-07, Tuesday](#id-section62)
     * [Entry 63: 2020-04-08, Wednesday](#id-section63)
    * [Entry 64: 2020-04-09, Thursday](#id-section64)
    * [Entry 65: 2020-04-10, Friday](#id-section65)
    * [Entry 66: 2020-04-13, Monday](#id-section66)
    * [Entry 67: 2020-04-14, Tuesday](#id-section67)
    * [Entry 68: 2020-04-15, Wednesday](#id-section68)
     * [Entry 69: 2020-04-16, Thursday](#id-section69)
    * [Entry 70: 2020-04-17, Friday](#id-section70)
    * [Entry 71: 2020-04-20, Monday](#id-section71)
    * [Entry 72: 2020-04-21, Tuesday](#id-section72)
    * [Entry 73: 2020-04-22, Wednesday](#id-section73)
    * [Entry 74: 2020-04-23, Thursday](#id-section74)
    * [Entry 75: 2020-04-24, Friday](#id-section75)
    * [Entry 76: 2020-04-27, Monday](#id-section76)
     * [Entry 77: 2020-04-28, Tuesday](#id-section77)
     * [Entry 78: 2020-04-29, Wednesday](#id-section78)
    * [Entry 79: 2020-04-30, Thursday](#id-section79)
    * [Entry 80: 2020-05-01, Friday](#id-section80)
    * [Entry 81: 2020-05-04, Monday](#id-section81)
    * [Entry 82: 2020-05-05, Tuesday](#id-section82)
    * [Entry 83: 2020-05-06, Wednesday](#id-section83)
    * [Entry 84: 2020-05-07, Thursday](#id-section84)
    * [Entry 85: 2020-05-08, Friday](#id-section85)

------
<div id='id-section1'/>   

### Entry 1: 2020-01-01, Wednesday.   



------
<div id='id-section2'/>   

### Entry 2: 2020-01-02, Thursday.   



------
<div id='id-section3'/>   

### Entry 3: 2020-01-03, Friday.   



------
<div id='id-section4'/>   

### Entry 4: 2020-01-06, Monday.   



------
<div id='id-section5'/>   

### Entry 5: 2020-01-07, Tuesday.   



------
<div id='id-section6'/>   

### Entry 6: 2020-01-08, Wednesday.   



------
<div id='id-section7'/>   

### Entry 7: 2020-01-09, Thursday.   



------
<div id='id-section8'/>   

### Entry 8: 2020-01-10, Friday.   



------
<div id='id-section9'/>   

### Entry 9: 2020-01-13, Monday.   

Fst as direct product of Wright's island model. each island has pop of same size so begs the question how much does drift alone (bc no selection in this model) affect allele freq differences in each pop and how does pop size decay this expected Fst

Fisher's thought on relative fitness of alleles: should see rapid fixation of selected alllele in any pop and therefore you would expect v little standing variation (save for minor allele sheltering in heterozygotes due to dominance)... SO why is there ever standing variation

ecological genomics is all about wtf is the expalanation for this standing variation 

molecular evolution:
M. Kimura: neutral theory of molecualr evolution: p(new mutation)= 1/2N = prob of fixation of mutation (assuming neutral)
    - enter modern central dogma: well tunrs out wobble exists so some mutations are synonimous |- dN/dS = Nmutations/N non-synom sites / N synonimous mutations / N synon sites = w
    w >> 1 positive slection
    w = 1 neutral
    w << 1 negative/purifying selection
    

            
            
Ecological genomics = molecular evolution + pop gen + ecology + NGS data


------
<div id='id-section10'/>   

### Entry 10: 2020-01-14, Tuesday.   



------
<div id='id-section11'/>   

### Entry 11: 2020-01-15, Wednesday.   

ILLumina:

shear genomic DNA into 200-300bp fragments
ligate adaptors 
apply to flowcell that contains lawn of complimentaary adaptors 
have adaptors with primers built in on both ends so bridge can form. can then create clusters of the same fragment via bridge amplification PCR
then sequenceing throug synthesis with flourencently-tagged bases (dNTPs) that have a built in terminator that can be cleaved before the next pulse of dNTPs

myseq: 30mill reads per run
hiseq: 3bill
novaseq 13 bill 
sanger: 400 


long read sequencing:

SMRT- single molecule realtime tech
    +pacbio
    + ONT
    
* Pacbio:
    + DNA strand is fed to fixed-position polymerase within a well that contains laser/camera. Still uses dNTP that are incorperated and floouresence is measured by camera. each dNTP is cleaved after incorperation. often do this with a circular DNA frag so that process can be repeated 
    + ONT uses nanopore and motor protein that accepts single DNA strand 
    
synthetic
    + illumina
    + 10xgenomics
    + both start with library of long fragments that are then separated, sheared and tagged so that short read sequencing can be used while keeping track of the original long fragment 
    

Throughput:
Illumina short read: 800-900Gb
pacbio: 1GB
ONT: 1.5GB

Error:
I: .1%
P: 1%
O: 2-13%

price:
I: 7$/GB
P: $1000/GB
O: %750

library prep:

# RNA-seq:
 tissue -> extraction -> quant -> rRNA depletion -> polyA enrichment (pull down of intact mature mRNA) -> fragmentation -> cDNA reverse transcription -> lig8 adaptors to both ends -> PCR amplification 

# GBS:
gDNA -> digestion -> number/mean length of fragments will depend on target seq of restriction enzyme -> ligate barcoded adaptors -> multiplex (pool individuals ) -> PCR 

 




------
<div id='id-section12'/>   

### Entry 12: 2020-01-16, Thursday.   



------
<div id='id-section13'/>   

### Entry 13: 2020-01-17, Friday.   



------
<div id='id-section14'/>   

### Entry 14: 2020-01-20, Monday.   


# BSeq:
where are methylated cytosines within my genome. aka, which cpg islands are methylated to inactivate a nearby promoter 
gDNA -> treat with sodiumbisulfite which will mehtylated cytosines into uracil -> PCR amplify -> sequence treated and untreated -> compare treated and untreated and look for TG rather in than CG in treated sample 


# CHIPseq: (chromatin immunoprecipitation)
gDNA -> treat to crosslink regulator proteins to DNA -> fragment DNA -> introduce antibody for protein of interest that are attached to beads -> pull down only DNA fragments that are bound to protein of interest -> precipitate, decouple, and sequence 

# ATAC-Seq: looking at chromatin accessability 
gDNA -> introduce synthetic transposon that will fragment only open chromatin and add adapters to fragments -> pcr -> sequence 

# HiC-seq: 
helps look at 3D structure of genome and partion cis and trans regulation:
crosslink all DNA that is touching eachother and pull them out -> biotnylate to form a chimeric combination of the 2 sequences -> sequence

------
<div id='id-section15'/>   

### Entry 15: 2020-01-21, Tuesday.   



------
<div id='id-section16'/>   

### Entry 16: 2020-01-22, Wednesday.   
# Amplicon Seq:
Amplicon= PCR product that usually contains repeat regions (either head-to-head repeat or inverted repeates)
used for deep coverage of specific area to look for rare variants 
helpful in metagenomics when you're just looking for one identifying region for community construction (ITS, 16srRNA)

lib prep uses pcr with target-specific primers, which is followed by an optional purification step and then another pcr for anealing barcodes (if you want to look at multiple genes per sample). no fragmentation needed in lib prep becasue pcr should be amplifying fragments that are already short enough for illumina 

# exome capture seq
* helpful for genetic mapping of tratis in big, confusing genomes 
* helpful for distilling sequenced variants down to stuff that's more likely to be causal 
* exons are more conserved than other regions, so this is helpful in phylogenetics too
* nice for aDNA bc WGS is annoying with poor sample quality
* lib prep: gDNA -> fragmentation to blunt ends -> adenine tail addition -> adaptors added to both ends fo fragments -> use custom probes to pull down exonic regions
ways to make probes:
-PCR: good for ~100 loci. cheaper option (in a per individual sense). basically the same as amplicon seq. 
-De Novo: good for thousands of loci (cheaper in a per probe sense) requires transcriptome data
-Divergent annotated genome: good for thousands of loci (cheaper in a per probe sense) requires annotated genome of related sp 
* no matter how you do it, you will be getting more than just the exome bc the probes will bind to exomic regions BUT they will pull down the entire fragment, which could contain introns
* best to design probes using multiple transcriptomes 


------
<div id='id-section17'/>   

### Entry 17: 2020-01-23, Thursday.   



------
<div id='id-section18'/>   

### Entry 18: 2020-01-24, Friday.   



------
<div id='id-section19'/>   

### Entry 19: 2020-01-27, Monday.   

population genomics: selection and drift across the genome 

damn hard to separate the genomic signal of selection from the genomic signal of changes in distribution from changes in selection 

genome-wide methodology is crucial because there is generally variation in polymorphsim across different regions of the genome, so you will be biasing your inference if you only focuss on one region 

effect of drift is global, while effect of selection is local <- struggling to agree with this 

* demographic history:
    + effective populaiton size
    + migration (gene flow) among populations
    + divergence time
    + coalescent theory (Kingman, Watterson, Tajima, Hudson)
        + you expect 2*Ne allele copies in a population. for 2 individuals, the odds that the alleles that they have descended from common ancestor in the past generation = 1/2Ne
        + coalesence event = two individuals inheret an allele copy from a common ancestor 
        + so this implies that rate of coalesence is dependent on pop size 
        + requires a wright fisher population (constant in size and population)
        + allele copies you see in a pop are just the ones that have been passed on 
        + for any given generation of a population, there is a number of generations in the past that you would have to go to find the common ancestor of all of the allelic copies present in the populaiton 
        
* as a population grows, the more rare alleles you see. A bottle necked pop tends to lose rare alleles and maintain common ones
    +  so a population coming out of a selective sweep can look like a population boom
    + so need to measure the hypothesis of a selective sweep against the background of coalesence 

* reduction in nucleotide diversity of a region of genome due to selective sweep will increase LD in that region 

FDR explained: if I perform the same test of the same statistic for 100 loci, and each time I have a P value cuttoff of .05 for singnificane, then I should have 5 loci that were incorrectly called significant 

reverse ecology: approach genomic data agnostically and then let outliers generate hypothese about whats going on ecologically/physiologically 



3' seq increases your power to detect DE at low coverage bc you aren't diluting your coverage across the whole transcript length



------
<div id='id-section20'/>   

### Entry 20: 2020-01-28, Tuesday.   



------
<div id='id-section21'/>   

### Entry 21: 2020-01-29, Wednesday.   
# in class 1/29 "popgen day 1"

Q score == prob that sequencer got basecall wrong

I am woking with the XSK reads 
```{bash, eval=F}

# note that server is running Red Hat 7.7

# fastq files for exome capture located here
cd /data/project_data/RS_ExomeSeq/fastq/edge_fastq/

```


heres the script we wrote for fastqc (fastqc.sh)


```{bash, eval=F}

#!/bin/bash

cd ~/Ecological-Genomics/myresults

mkdir fastqc

for file in /data/project_data/RS_ExomeSeq/fastq/edge_fastq/XSK*fastq.gz

do

fastqc ${file} -o fastqc/

done
```

then hit it with a chmod u+x

```{bash, eval=F}
./fastqc.sh
```


then we used trimmomatic with the script (Ecological-Genomics/myscripts/trim_loop.sh)

homework = run fastqc on trimmed seqs 


```{bash, eval=F}
cp /data/scripts/process_bam.sh myscripts/
```

here's the script (after I edited it)

```{bash, eval=F}
#!/bin/bash

# We'll use this a wrapper to run our different mapping scripts

# Path to my repo
myrepo="/users/b/w/bwworthi/Ecological-Genomics"

# echo ${myrepo}  <- to call my repo

# My population:
mypop="XSK"

# Directory to our cleaned and paired reads:
input="/data/project_data/RS_ExomeSeq/fastq/edge_fastq/pairedcleanreads/${mypop}"

# Directory to store the outputs of our mapping
# This part below goes to the common space
output="/data/project_data/RS_ExomeSeq/mapping"

# Run mapping.sh
source ./mapping.sh

# Run the post-processing steps
source ./process_bam.sh
```



now  run the mapping pipeline script 

```{bash, eval=F}
# from within screen
cd myscripts/

bash mypipeline.sh

```


------
<div id='id-section22'/>   

### Entry 22: 2020-01-30, Thursday.   



------
<div id='id-section23'/>   

### Entry 23: 2020-01-31, Friday.   

find the flag code of the last read in a sam file 
then you can search it on here https://broadinstitute.github.io/picard/explain-flags.html

```{bash, eval=F}
tail -n 1 XSK_01.sam | awk '{print $2}'
```

flagsats for each bam file 

heres's the script 

```{bash, eval=F}
#!/bin/bash

# set repo

myrepo="/users/b/w/bwworthi/Ecological-Genomics/"

mypop="XSK"

output="/data/project_data/RS_ExomeSeq/mapping/"

echo "Num.reads R1 R2 Paired MateMapped Singletons MateMappedDiffChr" > ${myrepo}/myresults/${mypop}.flagstats.txt

for file in ${output}/BWA/${mypop}*.sorted.rmdup.bam

	do 
	
f=${file/.sorted.rmdup.bam}
name=`basename ${f}`
echo $name >> ${myrepo}/myresults/${mypop}.names.txt

# take flagstat output, grab only rows between 6 and 12 and then take first col and flip it into a row 
samtools flagstat ${file} | awk 'NR>=6&&NR<=12 {print $1}' | column -x 

done >> ${myrepo}/myresults/${mypop}.flagstats.txt

# find depth of coverage for these

for file in ${output}/BWA/${mypop}*.sorted.rmdup.bam

	do
	# find average depth across all locations 
	samtools depth ${file} | awk '{sum+=$3} END {print sum/NR}'
	done >> ${myrepo}/myresults/${mypop}.coverage.txt
```


```{bash, eval=F}
bash myscripts/bamstats.sh
```

------
<div id='id-section24'/>   

### Entry 24: 2020-02-03, Monday.   



------
<div id='id-section25'/>   

### Entry 25: 2020-02-04, Tuesday.   



------
<div id='id-section26'/>   

### Entry 26: 2020-02-05, Wednesday.   

working with low coverage (our mean is ~3.5) data makes it hard to confidently call genotypes at ambiguous sites, this is why we use ANGSD because it doesn't hard call genos, it just uses the 3 probabilites of hetero, homo minor, homo major 
aka "genotype-free pop gen"

need to copy some of the scripts used above into the RMD

```{bash, eval=F}
myrepo="/users/b/w/bwworthi/Ecological-Genomics"

mkdir ${myrepo}/myresults/ANGSD

output="${myrepo}/myresults/ANGSD"

mypop="XSK"

# grab all the names of all bam files for my pop
ls /data/project_data/RS_ExomeSeq/mapping/BWA/${mypop}_*sorted.rm*.bam >${output}/${mypop}_bam.list

# get ref genome 

REF="/data/project_data/RS_ExomeSeq/ReferenceGenomes/Pabies1.0-genome_reduced.fa"

# Estimating GL's and allele frequencies for all sites with ANGSD
# notice in second line we're calling the ref genome he ancestral state for all sites (which is BS but our only option)
# we establish min mapping and read quality 
# min depth is set to 3 based on our expected sequencing depth


ANGSD -b ${output}/${mypop}_bam.list \
-ref ${REF} -anc ${REF} \
-out ${output}/${mypop}_allsites \
-nThreads 1 \
-remove_bads 1 \
-C 50 \
-baq 1 \
-minMapQ 20 \
-minQ 20 \
-setMinDepth 3 \
-minInd 2 \
-setMinDepthInd 1 \
-setMaxDepthInd 17 \
-skipTriallelic 1 \
-GL 1 \
-doCounts 1 \
-doMajorMinor 1 \
-doMaf 1 \
-doSaf 1 \
-doHWE 1 \
# -SNP_pval 1e-6


# now re- doing bc our ref is not truly ancestral and we want to fold over the frequency spectrum 

# NOTE THAT I DID NOT EDIT ANGSD_mypop.sh to include this

ANGSD -b ${output}/${mypop}_bam.list \
-ref ${REF} -anc ${REF} \
-out ${output}/${mypop}_outFold \
-nThreads 4 \
-remove_bads 1 \
-C 50 \
-baq 1 \
-minMapQ 20 \
-minQ 20 \
-setMinDepth 3 \
-minInd 2 \
-setMinDepthInd 1 \
-setMaxDepthInd 17 \
-skipTriallelic 1 \
-GL 1 \
-doCounts 1 \
-doMajorMinor 1 \
-doMaf 1 \
-doSaf 1 \
-fold 1  

```


------
<div id='id-section27'/>   

### Entry 27: 2020-02-06, Thursday.   



------
<div id='id-section28'/>   

### Entry 28: 2020-02-07, Friday.   



------
<div id='id-section29'/>   

### Entry 29: 2020-02-10, Monday.   



------
<div id='id-section30'/>   

### Entry 30: 2020-02-11, Tuesday.   



------
<div id='id-section31'/>   

### Entry 31: 2020-02-12, Wednesday.   



------
<div id='id-section32'/>   

### Entry 32: 2020-02-13, Thursday.   



------
<div id='id-section33'/>   

### Entry 33: 2020-02-14, Friday.   



------
<div id='id-section34'/>   

### Entry 34: 2020-02-17, Monday.   



------
<div id='id-section35'/>   

### Entry 35: 2020-02-18, Tuesday.   



------
<div id='id-section36'/>   

### Entry 36: 2020-02-19, Wednesday.   

site freqency spectrum:

x axis = frequency of derived allele. units are 2*N (2 bc assuming diploid), so if some derived allele is fixed in the population, if will have a requnecy of 2N (everyone is homozygous for it). 
y axis = proportion of total alleles that fall into each level of frequency 

expectation based on coalescent theory == negative poisson looking histogram, as we would expect most derived allels to be present at low frequency

our issue: spike of high freqency for loci that are polypmorphic in everyone
    + cause = our assumption that reference is ancestral is wrong
    
solution= re run angsd but make SFS based on minor allele rather than derived allele which will essentially fold the SFS  over at x =1N (N = total # individuals)

note that a selective sweep will produce an SFS that has many more common and rare derived allleles than expected under the neutral model.
...also note that a selective sweep will have a larger effect on Tajima's estimator than on waterson's theta. 

theta = the expected number of mutations within a linage. theta=4Nut where t is divergence time and u is mutation rate 
pi = number of pairwise diffs 

theta estimated from pi is called tajima's estimator 

* tajima's D:
    + used to decetect deviations from the distribution of allele frequencies that we would expect under neutrality 
    + requires 2 other stats: Waterson's theta (number of segregating sites) and Tajima's estimator (based on average number of pairwise differences)
    + both stats are expected to give the same estimate under neutrality, but when a slecective sweep happens, wtersons will be greater than taj's. the reverse is true for balancing selection. 
    + Taj's D = (Taj's estimator - waterson's theta)/sqrt(var(Taj's estimator - waterson's theta))
    + =0 under neutrality
    + =+ if balancing slection
    + =- if recent selective sweep 

plan going forward: site freq spectrum estimate -> estimate real sfs -> calculate theta (doTheta) -> theta_stats -> finally have measure of nucleotide diversity 

------
<div id='id-section37'/>   

### Entry 37: 2020-02-20, Thursday.   



------
<div id='id-section38'/>   

### Entry 38: 2020-02-21, Friday.   



------
<div id='id-section39'/>   

### Entry 39: 2020-02-24, Monday.   

reverse ecology: letting signatures of selection in genetic data inform you as to what phenotypes are ecologically important 

Transcriptomics: "Experimentally hold/control envrironmental condtitions constant to reveal genetically-controled diff. of phenotypes at the molecular level" (?????????????????)

Could do proteomics but it's more expensive and can't look for mutations (????)

factors affecting expression:
* common garden
* Treatments
* Populations
* Tissue/cell
* Life history 
* Transgenerational environment
* Sex, reproductive stage


------
<div id='id-section40'/>   

### Entry 40: 2020-02-25, Tuesday.   



------
<div id='id-section41'/>   

### Entry 41: 2020-02-26, Wednesday.   



------
<div id='id-section42'/>   

### Entry 42: 2020-02-27, Thursday.   



------
<div id='id-section43'/>   

### Entry 43: 2020-02-28, Friday.   



------
<div id='id-section44'/>   

### Entry 44: 2020-03-02, Monday.   



------
<div id='id-section45'/>   

### Entry 45: 2020-03-03, Tuesday.   



------
<div id='id-section46'/>   

### Entry 46: 2020-03-04, Wednesday.   



------
<div id='id-section47'/>   

### Entry 47: 2020-03-05, Thursday.   



------
<div id='id-section48'/>   

### Entry 48: 2020-03-06, Friday.   



------
<div id='id-section49'/>   

### Entry 49: 2020-03-09, Monday.   



------
<div id='id-section50'/>   

### Entry 50: 2020-03-10, Tuesday.   



------
<div id='id-section51'/>   

### Entry 51: 2020-03-11, Wednesday.   



------
<div id='id-section52'/>   

### Entry 52: 2020-03-12, Thursday.   



------
<div id='id-section53'/>   

### Entry 53: 2020-03-13, Friday.   



------
<div id='id-section54'/>   

### Entry 54: 2020-03-16, Monday.   



------
<div id='id-section55'/>   

### Entry 55: 2020-03-17, Tuesday.   



------
<div id='id-section56'/>   

### Entry 56: 2020-03-18, Wednesday.   



------
<div id='id-section57'/>   

### Entry 57: 2020-03-19, Thursday.   



------
<div id='id-section58'/>   

### Entry 58: 2020-03-20, Friday.   



------
<div id='id-section59'/>   

### Entry 59: 2020-03-23, Monday.   



------
<div id='id-section60'/>   

### Entry 60: 2020-03-24, Tuesday.   



------
<div id='id-section61'/>   

### Entry 61: 2020-03-25, Wednesday.  

* changes in gene expression not due to changes in sequence 
    + "stable, long-term alterations in the trancriptional ptential of a cell that are not necessarily heritable"
    + so we usually partition it as Ve

* Mechanisms:
    + phosphorylation of DNA or Protein 
    + miRNA or siRNA lead to transcription withiout translation
    + Histone modification: conversion to euchromatin allows transcription
    
* Methylation:
    + can cause irreverible conversion to thymine that I don't understand 
    + High methylation of promoter and enhancer = repression of expression via inhibition of TF binding
    + gene body methylation is oposite of promoter/enhancer methylation; it increases expression of gene in question 
        + can also affect splicing 
    + in intergenic regions, can also act to silence TEs, Steve hypothesizes that this might be origin for evolution of methylation 

* BSseq
    + sodium bisulfite changes non-mtehylated cytosine to uracil 
    + pcr amplification converts them to T




experimental evo experiment where you expose copipods to control, high tempm high co2 and temp + high co2

used targeted sequencing of cpg sites using restriction enzymes that cut at ccgg
    + this enzyme cuts at cpgs BUT it is not sensitive to methylation
    
    use spike in of DNA that is known to be unmethylated to use as measure of C-T conversion efficiency in BS seq 
    


when we align these reads, we need a version of the genome where we convert Cs to Ts and Ts to As 

then need to fully change the reads the same way, and then keep track of which were changed (program keeps track of this)

------
<div id='id-section62'/>   

### Entry 62: 2020-03-26, Thursday.   



------
<div id='id-section63'/>   

### Entry 63: 2020-03-27, Friday.   



------
<div id='id-section64'/>   

### Entry 64: 2020-03-30, Monday.   



------
<div id='id-section65'/>   

### Entry 65: 2020-03-31, Tuesday.   



------
<div id='id-section66'/>   

### Entry 66: 2020-04-01, Wednesday.   



------
<div id='id-section67'/>   

### Entry 67: 2020-04-02, Thursday.   



------
<div id='id-section68'/>   

### Entry 68: 2020-04-03, Friday.   



------
<div id='id-section69'/>   

### Entry 69: 2020-04-06, Monday.   



------
<div id='id-section70'/>   

### Entry 70: 2020-04-07, Tuesday.   



------
<div id='id-section71'/>   

### Entry 71: 2020-04-08, Wednesday.   



------
<div id='id-section72'/>   

### Entry 72: 2020-04-09, Thursday.   



------
<div id='id-section73'/>   

### Entry 73: 2020-04-10, Friday.   



------
<div id='id-section74'/>   

### Entry 74: 2020-04-13, Monday.   



------
<div id='id-section75'/>   

### Entry 75: 2020-04-14, Tuesday.   



------
<div id='id-section76'/>   

### Entry 76: 2020-04-15, Wednesday.   



------
<div id='id-section77'/>   

### Entry 77: 2020-04-16, Thursday.   



------
<div id='id-section78'/>   

### Entry 78: 2020-04-17, Friday.   



------
<div id='id-section79'/>   

### Entry 79: 2020-04-20, Monday.   



------
<div id='id-section80'/>   

### Entry 80: 2020-04-21, Tuesday.   



------
<div id='id-section81'/>   

### Entry 81: 2020-04-22, Wednesday.   



------
<div id='id-section82'/>   

### Entry 82: 2020-04-23, Thursday.   



------
<div id='id-section83'/>   

### Entry 83: 2020-04-24, Friday.   



------
<div id='id-section84'/>   

### Entry 84: 2020-04-27, Monday.   



------
<div id='id-section85'/>   

### Entry 85: 2020-04-28, Tuesday.   



------
<div id='id-section86'/>   

### Entry 86: 2020-04-29, Wednesday.   



------
<div id='id-section87'/>   

### Entry 87: 2020-04-30, Thursday.   



------
<div id='id-section88'/>   

### Entry 88: 2020-05-01, Friday.   



------
<div id='id-section89'/>   

### Entry 89: 2020-05-04, Monday.   



------
<div id='id-section90'/>   

### Entry 90: 2020-05-05, Tuesday.   



------
<div id='id-section91'/>   

### Entry 91: 2020-05-06, Wednesday.   



------
<div id='id-section92'/>   

### Entry 92: 2020-05-07, Thursday.   



------
<div id='id-section93'/>   

### Entry 93: 2020-05-08, Friday.   



------
<div id='id-section94'/>   

### Entry 94: 2020-05-11, Monday.   



------
<div id='id-section95'/>   

### Entry 95: 2020-05-12, Tuesday.   



------
<div id='id-section96'/>   

### Entry 96: 2020-05-13, Wednesday.   



------
<div id='id-section97'/>   

### Entry 97: 2020-05-14, Thursday.   



------
<div id='id-section98'/>   

### Entry 98: 2020-05-15, Friday.   



------
<div id='id-section99'/>   

### Entry 99: 2020-05-18, Monday.   



------
<div id='id-section100'/>   

### Entry 100: 2020-05-19, Tuesday.   



------
<div id='id-section101'/>   

### Entry 101: 2020-05-20, Wednesday.   



------
<div id='id-section102'/>   

### Entry 102: 2020-05-21, Thursday.   



------
<div id='id-section103'/>   

### Entry 103: 2020-05-22, Friday.   



------
<div id='id-section104'/>   

### Entry 104: 2020-05-25, Monday.   



------
<div id='id-section105'/>   

### Entry 105: 2020-05-26, Tuesday.   



------
<div id='id-section106'/>   

### Entry 106: 2020-05-27, Wednesday.   



------
<div id='id-section107'/>   

### Entry 107: 2020-05-28, Thursday.   



------
<div id='id-section108'/>   

### Entry 108: 2020-05-29, Friday.   



------
<div id='id-section109'/>   

### Entry 109: 2020-06-01, Monday.   



------
<div id='id-section110'/>   

### Entry 110: 2020-06-02, Tuesday.   



------
<div id='id-section111'/>   

### Entry 111: 2020-06-03, Wednesday.   



------
<div id='id-section112'/>   

### Entry 112: 2020-06-04, Thursday.   



------
<div id='id-section113'/>   

### Entry 113: 2020-06-05, Friday.   



------
<div id='id-section114'/>   

### Entry 114: 2020-06-08, Monday.   



------
<div id='id-section115'/>   

### Entry 115: 2020-06-09, Tuesday.   



------
<div id='id-section116'/>   

### Entry 116: 2020-06-10, Wednesday.   



------
<div id='id-section117'/>   

### Entry 117: 2020-06-11, Thursday.   



------
<div id='id-section118'/>   

### Entry 118: 2020-06-12, Friday.   



------
<div id='id-section119'/>   

### Entry 119: 2020-06-15, Monday.   



------
<div id='id-section120'/>   

### Entry 120: 2020-06-16, Tuesday.   



------
<div id='id-section121'/>   

### Entry 121: 2020-06-17, Wednesday.   



------
<div id='id-section122'/>   

### Entry 122: 2020-06-18, Thursday.   



------
<div id='id-section123'/>   

### Entry 123: 2020-06-19, Friday.   



------
<div id='id-section124'/>   

### Entry 124: 2020-06-22, Monday.   



------
<div id='id-section125'/>   

### Entry 125: 2020-06-23, Tuesday.   



------
<div id='id-section126'/>   

### Entry 126: 2020-06-24, Wednesday.   



------
<div id='id-section127'/>   

### Entry 127: 2020-06-25, Thursday.   



------
<div id='id-section128'/>   

### Entry 128: 2020-06-26, Friday.   



------
<div id='id-section129'/>   

### Entry 129: 2020-06-29, Monday.   



------
<div id='id-section130'/>   

### Entry 130: 2020-06-30, Tuesday.   



------
<div id='id-section131'/>   

### Entry 131: 2020-07-01, Wednesday.   



------
<div id='id-section132'/>   

### Entry 132: 2020-07-02, Thursday.   



------
<div id='id-section133'/>   

### Entry 133: 2020-07-03, Friday.   



------
<div id='id-section134'/>   

### Entry 134: 2020-07-06, Monday.   



------
<div id='id-section135'/>   

### Entry 135: 2020-07-07, Tuesday.   



------
<div id='id-section136'/>   

### Entry 136: 2020-07-08, Wednesday.   



------
<div id='id-section137'/>   

### Entry 137: 2020-07-09, Thursday.   



------
<div id='id-section138'/>   

### Entry 138: 2020-07-10, Friday.   



------
<div id='id-section139'/>   

### Entry 139: 2020-07-13, Monday.   



------
<div id='id-section140'/>   

### Entry 140: 2020-07-14, Tuesday.   



------
<div id='id-section141'/>   

### Entry 141: 2020-07-15, Wednesday.   



------
<div id='id-section142'/>   

### Entry 142: 2020-07-16, Thursday.   



------
<div id='id-section143'/>   

### Entry 143: 2020-07-17, Friday.   



------
<div id='id-section144'/>   

### Entry 144: 2020-07-20, Monday.   



------
<div id='id-section145'/>   

### Entry 145: 2020-07-21, Tuesday.   



------
<div id='id-section146'/>   

### Entry 146: 2020-07-22, Wednesday.   



------
<div id='id-section147'/>   

### Entry 147: 2020-07-23, Thursday.   



------
<div id='id-section148'/>   

### Entry 148: 2020-07-24, Friday.   



------
<div id='id-section149'/>   

### Entry 149: 2020-07-27, Monday.   



------
<div id='id-section150'/>   

### Entry 150: 2020-07-28, Tuesday.   



------
<div id='id-section151'/>   

### Entry 151: 2020-07-29, Wednesday.   



------
<div id='id-section152'/>   

### Entry 152: 2020-07-30, Thursday.   



------
<div id='id-section153'/>   

### Entry 153: 2020-07-31, Friday.   



------
<div id='id-section154'/>   

### Entry 154: 2020-08-03, Monday.   



------
<div id='id-section155'/>   

### Entry 155: 2020-08-04, Tuesday.   



------
<div id='id-section156'/>   

### Entry 156: 2020-08-05, Wednesday.   



------
<div id='id-section157'/>   

### Entry 157: 2020-08-06, Thursday.   



------
<div id='id-section158'/>   

### Entry 158: 2020-08-07, Friday.   



------
<div id='id-section159'/>   

### Entry 159: 2020-08-10, Monday.   



------
<div id='id-section160'/>   

### Entry 160: 2020-08-11, Tuesday.   



------
<div id='id-section161'/>   

### Entry 161: 2020-08-12, Wednesday.   



------
<div id='id-section162'/>   

### Entry 162: 2020-08-13, Thursday.   



------
<div id='id-section163'/>   

### Entry 163: 2020-08-14, Friday.   



------
<div id='id-section164'/>   

### Entry 164: 2020-08-17, Monday.   



------
<div id='id-section165'/>   

### Entry 165: 2020-08-18, Tuesday.   



------
<div id='id-section166'/>   

### Entry 166: 2020-08-19, Wednesday.   



------
<div id='id-section167'/>   

### Entry 167: 2020-08-20, Thursday.   



------
<div id='id-section168'/>   

### Entry 168: 2020-08-21, Friday.   



------
<div id='id-section169'/>   

### Entry 169: 2020-08-24, Monday.   



------
<div id='id-section170'/>   

### Entry 170: 2020-08-25, Tuesday.   



------
<div id='id-section171'/>   

### Entry 171: 2020-08-26, Wednesday.   



------
<div id='id-section172'/>   

### Entry 172: 2020-08-27, Thursday.   



------
<div id='id-section173'/>   

### Entry 173: 2020-08-28, Friday.   



------
<div id='id-section174'/>   

### Entry 174: 2020-08-31, Monday.   



------
<div id='id-section175'/>   

### Entry 175: 2020-09-01, Tuesday.   



------
<div id='id-section176'/>   

### Entry 176: 2020-09-02, Wednesday.   



------
<div id='id-section177'/>   

### Entry 177: 2020-09-03, Thursday.   



------
<div id='id-section178'/>   

### Entry 178: 2020-09-04, Friday.   



------
<div id='id-section179'/>   

### Entry 179: 2020-09-07, Monday.   



------
<div id='id-section180'/>   

### Entry 180: 2020-09-08, Tuesday.   



------
<div id='id-section181'/>   

### Entry 181: 2020-09-09, Wednesday.   



------
<div id='id-section182'/>   

### Entry 182: 2020-09-10, Thursday.   



------
<div id='id-section183'/>   

### Entry 183: 2020-09-11, Friday.   



------
<div id='id-section184'/>   

### Entry 184: 2020-09-14, Monday.   



------
<div id='id-section185'/>   

### Entry 185: 2020-09-15, Tuesday.   



------
<div id='id-section186'/>   

### Entry 186: 2020-09-16, Wednesday.   



------
<div id='id-section187'/>   

### Entry 187: 2020-09-17, Thursday.   



------
<div id='id-section188'/>   

### Entry 188: 2020-09-18, Friday.   



------
<div id='id-section189'/>   

### Entry 189: 2020-09-21, Monday.   



------
<div id='id-section190'/>   

### Entry 190: 2020-09-22, Tuesday.   



------
<div id='id-section191'/>   

### Entry 191: 2020-09-23, Wednesday.   



------
<div id='id-section192'/>   

### Entry 192: 2020-09-24, Thursday.   



------
<div id='id-section193'/>   

### Entry 193: 2020-09-25, Friday.   



------
<div id='id-section194'/>   

### Entry 194: 2020-09-28, Monday.   



------
<div id='id-section195'/>   

### Entry 195: 2020-09-29, Tuesday.   



------
<div id='id-section196'/>   

### Entry 196: 2020-09-30, Wednesday.   



------
<div id='id-section197'/>   

### Entry 197: 2020-10-01, Thursday.   



------
<div id='id-section198'/>   

### Entry 198: 2020-10-02, Friday.   



------
<div id='id-section199'/>   

### Entry 199: 2020-10-05, Monday.   



------
<div id='id-section200'/>   

### Entry 200: 2020-10-06, Tuesday.   



------
<div id='id-section201'/>   

### Entry 201: 2020-10-07, Wednesday.   



------
<div id='id-section202'/>   

### Entry 202: 2020-10-08, Thursday.   



------
<div id='id-section203'/>   

### Entry 203: 2020-10-09, Friday.   



------
<div id='id-section204'/>   

### Entry 204: 2020-10-12, Monday.   



------
<div id='id-section205'/>   

### Entry 205: 2020-10-13, Tuesday.   



------
<div id='id-section206'/>   

### Entry 206: 2020-10-14, Wednesday.   



------
<div id='id-section207'/>   

### Entry 207: 2020-10-15, Thursday.   



------
<div id='id-section208'/>   

### Entry 208: 2020-10-16, Friday.   



------
<div id='id-section209'/>   

### Entry 209: 2020-10-19, Monday.   



------
<div id='id-section210'/>   

### Entry 210: 2020-10-20, Tuesday.   



------
<div id='id-section211'/>   

### Entry 211: 2020-10-21, Wednesday.   



------
<div id='id-section212'/>   

### Entry 212: 2020-10-22, Thursday.   



------
<div id='id-section213'/>   

### Entry 213: 2020-10-23, Friday.   



------
<div id='id-section214'/>   

### Entry 214: 2020-10-26, Monday.   



------
<div id='id-section215'/>   

### Entry 215: 2020-10-27, Tuesday.   



------
<div id='id-section216'/>   

### Entry 216: 2020-10-28, Wednesday.   



------
<div id='id-section217'/>   

### Entry 217: 2020-10-29, Thursday.   



------
<div id='id-section218'/>   

### Entry 218: 2020-10-30, Friday.   



------
<div id='id-section219'/>   

### Entry 219: 2020-11-02, Monday.   



------
<div id='id-section220'/>   

### Entry 220: 2020-11-03, Tuesday.   



------
<div id='id-section221'/>   

### Entry 221: 2020-11-04, Wednesday.   



------
<div id='id-section222'/>   

### Entry 222: 2020-11-05, Thursday.   



------
<div id='id-section223'/>   

### Entry 223: 2020-11-06, Friday.   



------
<div id='id-section224'/>   

### Entry 224: 2020-11-09, Monday.   



------
<div id='id-section225'/>   

### Entry 225: 2020-11-10, Tuesday.   



------
<div id='id-section226'/>   

### Entry 226: 2020-11-11, Wednesday.   



------
<div id='id-section227'/>   

### Entry 227: 2020-11-12, Thursday.   



------
<div id='id-section228'/>   

### Entry 228: 2020-11-13, Friday.   



------
<div id='id-section229'/>   

### Entry 229: 2020-11-16, Monday.   



------
<div id='id-section230'/>   

### Entry 230: 2020-11-17, Tuesday.   



------
<div id='id-section231'/>   

### Entry 231: 2020-11-18, Wednesday.   



------
<div id='id-section232'/>   

### Entry 232: 2020-11-19, Thursday.   



------
<div id='id-section233'/>   

### Entry 233: 2020-11-20, Friday.   



------
<div id='id-section234'/>   

### Entry 234: 2020-11-23, Monday.   



------
<div id='id-section235'/>   

### Entry 235: 2020-11-24, Tuesday.   



------
<div id='id-section236'/>   

### Entry 236: 2020-11-25, Wednesday.   



------
<div id='id-section237'/>   

### Entry 237: 2020-11-26, Thursday.   



------
<div id='id-section238'/>   

### Entry 238: 2020-11-27, Friday.   



------
<div id='id-section239'/>   

### Entry 239: 2020-11-30, Monday.   



------
<div id='id-section240'/>   

### Entry 240: 2020-12-01, Tuesday.   



------
<div id='id-section241'/>   

### Entry 241: 2020-12-02, Wednesday.   



------
<div id='id-section242'/>   

### Entry 242: 2020-12-03, Thursday.   



------
<div id='id-section243'/>   

### Entry 243: 2020-12-04, Friday.   



------
<div id='id-section244'/>   

### Entry 244: 2020-12-07, Monday.   



------
<div id='id-section245'/>   

### Entry 245: 2020-12-08, Tuesday.   



------
<div id='id-section246'/>   

### Entry 246: 2020-12-09, Wednesday.   



------
<div id='id-section247'/>   

### Entry 247: 2020-12-10, Thursday.   



------
<div id='id-section248'/>   

### Entry 248: 2020-12-11, Friday.   



------
<div id='id-section249'/>   

### Entry 249: 2020-12-14, Monday.   



------
<div id='id-section250'/>   

### Entry 250: 2020-12-15, Tuesday.   



------
<div id='id-section251'/>   

### Entry 251: 2020-12-16, Wednesday.   



------
<div id='id-section252'/>   

### Entry 252: 2020-12-17, Thursday.   



------
<div id='id-section253'/>   

### Entry 253: 2020-12-18, Friday.   



------
<div id='id-section254'/>   

### Entry 254: 2020-12-21, Monday.   



------
<div id='id-section255'/>   

### Entry 255: 2020-12-22, Tuesday.   



------
<div id='id-section256'/>   

### Entry 256: 2020-12-23, Wednesday.   



------
<div id='id-section257'/>   

### Entry 257: 2020-12-24, Thursday.   



------
<div id='id-section258'/>   

### Entry 258: 2020-12-25, Friday.   



------
<div id='id-section259'/>   

### Entry 259: 2020-12-28, Monday.   



------
<div id='id-section260'/>   

### Entry 260: 2020-12-29, Tuesday.   



------
<div id='id-section261'/>   

### Entry 261: 2020-12-30, Wednesday.   



------
<div id='id-section262'/>   

### Entry 262: 2020-12-31, Thursday.   

